# CD持续交付
#  - 部署到Github Pages
#  - 部署到Vercel托管平台
#  - 发布新的Github Release
# 参考：https://v2.vuepress.vuejs.org/zh/guide/deployment.html#github-pages
#

name: CD

on:
  push:
    branches:
      - next
  workflow_dispatch:

jobs:
  # 版本发布
  release:
    name: 创建Github发布
    runs-on: ubuntu-latest
    # 主库next且执行release更新时执行
    if: github.repository == '142vip/core-x' && startsWith(github.event.head_commit.message, 'chore(release):')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      # 安装PNPM
      - name: PNPM Install
        uses: pnpm/action-setup@v4
        with:
          version: 7.33.2

      # 安装Node环境
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          # 淘宝镜像加速
          registry-url: 'https://registry.npmmirror.com'
          # 缓存
          cache: pnpm

      # 下载依赖，并执行初始化脚本：钩子函数、思维导图构建
      - name: Install Dependencies
        run: |
          ./scripts/ci

      - name: Build All Packages
        run: |
          pnpm build

      # Github发布版本，并更新Release信息
      - name: Release New Version
        run: npx changelog
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
